import { Router } from "express";
import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, EmbedBuilder, PermissionFlagsBits, TextChannel } from "discord.js";
import { client } from "./bot.js";
import { guildUi, selectedGuild, selectedGuildId } from "./dashboard-context.js";
import { audit, one, query } from "./db.js";
import { commandData } from "./commands.js";
import { billingCommandData } from "./billing-commands.js";
import { featureCommandData } from "./feature-suite.js";
import { economyCommandData } from "./economy.js";
import { levelFromXp } from "./economy-core.js";

export const extrasRouter=Router();
const auth=(req:any,res:any,next:any)=>req.session?.user?next():res.redirect("/login");
extrasRouter.use(auth);
// legacy-control-redirects: the new /control workspace owns member and analytics navigation.
extrasRouter.get("/members",(req,res)=>res.redirect("/control/members"));
extrasRouter.get("/members/:id",(req,res)=>res.redirect("/control/members"));
extrasRouter.get("/analytics",(req,res)=>res.redirect("/control"));

function guild(req:any){return selectedGuild(req);}
async function health(req:any){const g=guild(req);if(!g)return{score:0,checks:[{ok:false,label:"Bot connected to Discord"}]};const settings=await query<any>(`SELECT feature_key,enabled,config FROM feature_settings WHERE guild_id=$1`,[g.id]);const m=new Map(settings.map(x=>[x.feature_key,x]));const welcome:any=m.get("welcome"),tickets:any=m.get("tickets"),automod:any=m.get("automod"),roles:any=m.get("role_menus"),billing=await one<any>(`SELECT count(*) total FROM billing_plans WHERE guild_id=$1 AND active=true`,[g.id]);const me=g.members.me;const economy=await one<any>(`SELECT enabled FROM economy_settings WHERE guild_id=$1`,[g.id]);
 const store=await one<any>(`SELECT count(*) total FROM store_items WHERE guild_id=$1 AND active=true`,[g.id]);
 const season=await one<any>(`SELECT id FROM economy_seasons WHERE guild_id=$1 AND active=true AND ends_at>now()`,[g.id]);
 const checks=[
 {ok:Boolean(me),label:"Bot connected to Discord"},{ok:Boolean(me?.permissions.has(PermissionFlagsBits.ManageRoles)),label:"Bot can manage roles"},{ok:Boolean(me?.permissions.has(PermissionFlagsBits.ManageChannels)),label:"Bot can manage channels"},
 {ok:Boolean(welcome?.config?.channelId),label:"Welcome channel selected",href:"/modules/welcome"},{ok:Boolean(tickets?.config?.categoryId&&tickets?.config?.staffRoleIds?.length),label:"Tickets configured",href:"/modules/tickets"},{ok:Boolean(automod?.config?.modLogChannelId),label:"Moderation log configured",href:"/modules/automod"},{ok:Boolean(roles?.config?.groups?.length),label:"Member role menu configured",href:"/modules/role_menus"},{ok:Number(billing?.total||0)>0,label:"Premium plan active",href:"/billing"},
 {ok:economy?.enabled!==false,label:"Community economy active",href:"/economy"},{ok:Number(store?.total||0)>0,label:"Rewards store has active items",href:"/economy"},{ok:Boolean(season),label:"Community season active",href:"/economy"}
 ];return{score:Math.round(checks.filter(x=>x.ok).length/checks.length*100),checks};}

extrasRouter.get("/setup",async(req:any,res)=>{res.render("setup",{user:req.session.user,...await guildUi(req),health:await health(req),guild:guild(req),saved:req.query.saved==="1",message:String(req.query.message||""),error:String(req.query.error||"")});});
extrasRouter.post("/setup/test/:feature",async(req:any,res)=>{try{const g=guild(req);if(!g)throw new Error("Bot is offline.");const key=String(req.params.feature),row=await one<any>(`SELECT config FROM feature_settings WHERE guild_id=$1 AND feature_key=$2`,[g.id,key]);let channelId="",text="",label="Test";if(key==="welcome"){channelId=row?.config?.channelId;text="🧪 **Welcome test**\nThis is how your welcome channel is connected.";label="Welcome test sent";}if(key==="automod"){channelId=row?.config?.modLogChannelId;text="🧪 **Automod test**\nModeration logging is working.";label="Mod log test sent";}if(key==="tickets"){channelId=row?.config?.logChannelId;text="🧪 **Ticket test**\nTicket logging is working.";label="Ticket log test sent";}if(!channelId)throw new Error("No destination channel is configured for that test.");const ch=await client.channels.fetch(channelId).catch(()=>null);if(!ch?.isTextBased())throw new Error("The configured channel is not available to the bot.");const me=g.members.me;const perms=me&&(ch as any).permissionsFor?.(me);if(perms&&(!perms.has(PermissionFlagsBits.ViewChannel)||!perms.has(PermissionFlagsBits.SendMessages)))throw new Error("The bot needs View Channel and Send Messages permission in that channel.");await (ch as TextChannel).send(text);res.redirect(`/setup?message=${encodeURIComponent(label)}`);}catch(err:any){console.error("Setup test failed",err);res.redirect(`/setup?error=${encodeURIComponent(err?.message||"Test failed")}`);}});
extrasRouter.post("/setup/publish-roles",async(req:any,res)=>{try{const g=guild(req);if(!g)throw new Error("Bot is offline.");const row=await one<any>(`SELECT config FROM feature_settings WHERE guild_id=$1 AND feature_key='role_menus'`,[g.id]);const cfg=row?.config||{};const ch=cfg.channelId?await client.channels.fetch(cfg.channelId).catch(()=>null):null;if(!ch?.isTextBased())throw new Error("Choose a role-menu channel first.");const me=g.members.me;if(!me)throw new Error("Bot member is unavailable.");const perms=(ch as any).permissionsFor?.(me);if(perms&&(!perms.has(PermissionFlagsBits.ViewChannel)||!perms.has(PermissionFlagsBits.SendMessages)))throw new Error("The bot needs View Channel and Send Messages permission in the role channel.");let posted=0;for(const group of cfg.groups||[]){const buttons=(group.roleIds||[]).map((id:string)=>{const role=g.roles.cache.get(id);return role&&!role.managed&&role.position<me.roles.highest.position?new ButtonBuilder().setCustomId(`role:${id}`).setLabel(role.name.slice(0,80)).setStyle(ButtonStyle.Secondary):null;}).filter((b):b is ButtonBuilder=>Boolean(b));if(!buttons.length)continue;const rows:ActionRowBuilder<ButtonBuilder>[]=[];for(let x=0;x<buttons.length;x+=5)rows.push(new ActionRowBuilder<ButtonBuilder>().addComponents(...buttons.slice(x,x+5)));await (ch as TextChannel).send({embeds:[new EmbedBuilder().setTitle(group.name).setDescription(group.maxSelect===1?"Choose your role below. Click again to remove it.":"Choose any roles that apply to you.")],components:rows.slice(0,5)});posted++;}if(!posted)throw new Error("No assignable roles are selected. Move the bot role above the member roles you want it to manage.");res.redirect("/modules/role_menus?saved=1");}catch(err:any){console.error("Role menu publish failed",err);res.redirect(`/setup?error=${encodeURIComponent(err?.message||"Could not publish role menu")}`);}});

extrasRouter.get("/members",async(req:any,res)=>{const q=String(req.query.q||"").trim().toLowerCase(),g=guild(req);let members:any[]=[];if(g){const all=await g.members.fetch().catch(()=>g.members.cache);members=[...all.values()].filter(m=>!m.user.bot&&(!q||m.displayName.toLowerCase().includes(q)||m.user.username.toLowerCase().includes(q))).slice(0,100);const ids=members.map(m=>m.id);const [stats,economy,streaks,prem]=await Promise.all([ids.length?query<any>(`SELECT * FROM member_stats WHERE guild_id=$1 AND user_id=ANY($2::text[])`,[g.id,ids]):[],ids.length?query<any>(`SELECT * FROM member_economy WHERE guild_id=$1 AND user_id=ANY($2::text[])`,[g.id,ids]):[],ids.length?query<any>(`SELECT * FROM member_streaks WHERE guild_id=$1 AND user_id=ANY($2::text[])`,[g.id,ids]):[],ids.length?query<any>(`SELECT discord_user_id,entitlement_key FROM entitlements WHERE guild_id=$1 AND discord_user_id=ANY($2::text[]) AND active=true AND (expires_at IS NULL OR expires_at>now())`,[g.id,ids]):[]]);members=members.map(m=>{const eco=economy.find(e=>e.user_id===m.id);return{id:m.id,name:m.displayName,username:m.user.username,joinedAt:m.joinedAt,roles:m.roles.cache.filter((r:any)=>r.id!==g.id).map((r:any)=>r.name),stats:stats.find(x=>x.user_id===m.id),economy:eco,level:levelFromXp(Number(eco?.xp_total||0)),streak:streaks.find(x=>x.user_id===m.id),premium:prem.find(p=>p.discord_user_id===m.id)};});}res.render("members",{user:req.session.user,members,q});});
extrasRouter.get("/members/:id",async(req:any,res)=>{const g=guild(req),id=req.params.id,m=g?await g.members.fetch(id).catch(()=>null):null;if(!m)return res.status(404).send("Member not found");const [stats,economy,streak,trades,calls,notes,warnings,tickets,subs,refs,achievements,quests,ledger]=await Promise.all([one<any>(`SELECT * FROM member_stats WHERE guild_id=$1 AND user_id=$2`,[g!.id,id]),one<any>(`SELECT * FROM member_economy WHERE guild_id=$1 AND user_id=$2`,[g!.id,id]),one<any>(`SELECT * FROM member_streaks WHERE guild_id=$1 AND user_id=$2`,[g!.id,id]),query<any>(`SELECT * FROM trade_journal WHERE guild_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 25`,[g!.id,id]),query<any>(`SELECT * FROM trade_calls WHERE guild_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 25`,[g!.id,id]),query<any>(`SELECT * FROM staff_notes WHERE guild_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 25`,[g!.id,id]),query<any>(`SELECT * FROM warnings WHERE guild_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 25`,[g!.id,id]),query<any>(`SELECT * FROM tickets WHERE guild_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 25`,[g!.id,id]),query<any>(`SELECT s.*,p.name plan_name FROM billing_subscriptions s LEFT JOIN billing_plans p ON p.id=s.plan_id WHERE s.guild_id=$1 AND s.discord_user_id=$2 ORDER BY s.updated_at DESC`,[g!.id,id]),query<any>(`SELECT * FROM referral_codes WHERE guild_id=$1 AND owner_discord_user_id=$2`,[g!.id,id]),query<any>(`SELECT a.*,d.name,d.icon,d.description FROM achievements a LEFT JOIN achievement_definitions d ON d.guild_id=a.guild_id AND d.achievement_key=a.achievement_key WHERE a.guild_id=$1 AND a.user_id=$2 ORDER BY a.awarded_at DESC`,[g!.id,id]),query<any>(`SELECT q.name,q.cadence,q.target,p.progress,p.completed_at,p.rewarded_at FROM member_quest_progress p JOIN quest_definitions q ON q.id=p.quest_id WHERE p.guild_id=$1 AND p.user_id=$2 ORDER BY p.updated_at DESC LIMIT 20`,[g!.id,id]),query<any>(`SELECT * FROM economy_ledger WHERE guild_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 20`,[g!.id,id])]);const xp=Number(economy?.xp_total||0),level=levelFromXp(xp),closedCalls=calls.filter((c:any)=>c.status!=="LIVE"),wins=closedCalls.filter((c:any)=>["HIT","PROFIT"].includes(c.status)).length;res.render("member",{user:req.session.user,member:m,stats,economy:economy||{},streak:streak||{},level,trades,calls,callAccuracy:closedCalls.length?Math.round(wins/closedCalls.length*100):0,notes,warnings,tickets,subs,refs,achievements,quests,ledger});});

extrasRouter.get("/analytics",async(req:any,res)=>{const g=guild(req);const [daily,topXp,topHelpful,topProfit,topCoins,summary]=await Promise.all([query<any>(`SELECT * FROM server_metrics_daily WHERE guild_id=$1 ORDER BY metric_date DESC LIMIT 30`,[selectedGuildId(req)]),query<any>(`SELECT user_id,xp_total xp FROM member_economy WHERE guild_id=$1 ORDER BY xp_total DESC LIMIT 10`,[selectedGuildId(req)]),query<any>(`SELECT * FROM member_stats WHERE guild_id=$1 ORDER BY thanks_received DESC LIMIT 10`,[selectedGuildId(req)]),query<any>(`SELECT user_id,COALESCE(sum(profit),0) profit FROM trade_journal WHERE guild_id=$1 AND status='CLOSED' GROUP BY user_id ORDER BY profit DESC LIMIT 10`,[selectedGuildId(req)]),query<any>(`SELECT user_id,coins_balance FROM member_economy WHERE guild_id=$1 ORDER BY coins_balance DESC LIMIT 10`,[selectedGuildId(req)]),one<any>(`SELECT (SELECT count(*) FROM trade_journal WHERE guild_id=$1) journal_trades,(SELECT COALESCE(sum(profit),0) FROM trade_journal WHERE guild_id=$1) tracked_profit,(SELECT count(*) FROM giveaways WHERE guild_id=$1) giveaways,(SELECT count(*) FROM scam_cases WHERE guild_id=$1) reports,(SELECT count(*) FROM referral_codes WHERE guild_id=$1) referrals,(SELECT COALESCE(sum(coins_balance),0) FROM member_economy WHERE guild_id=$1) coins_circulating,(SELECT count(*) FROM member_quest_progress WHERE guild_id=$1 AND rewarded_at IS NOT NULL) quests_completed`,[selectedGuildId(req)])]);res.render("analytics",{user:req.session.user,daily:daily.reverse(),topXp,topHelpful,topProfit,topCoins,summary:summary||{},guild:g});});

extrasRouter.get("/automation",async(req:any,res)=>{const gid=selectedGuildId(req);const [scheduled,giveaways]=await Promise.all([query<any>(`SELECT * FROM scheduled_messages WHERE guild_id=$1 ORDER BY id DESC`,[gid]),query<any>(`SELECT * FROM giveaways WHERE guild_id=$1 ORDER BY created_at DESC LIMIT 50`,[gid])]);res.render("automation",{user:req.session.user,scheduled,giveaways,...await guildUi(req)});});
extrasRouter.post("/automation/scheduled",async(req:any,res)=>{const gid=selectedGuildId(req),days=Array.isArray(req.body.days)?req.body.days:req.body.days?[req.body.days]:[];const dow=days.length?days.join(","):"*",hour=Math.max(0,Math.min(23,Number(req.body.hour||0))),minute=Math.max(0,Math.min(59,Number(req.body.minute||0)));await query(`INSERT INTO scheduled_messages(guild_id,name,channel_id,cron_expression,content,enabled) VALUES($1,$2,$3,$4,$5,true)`,[gid,String(req.body.name||"Scheduled post"),String(req.body.channelId),`${minute} ${hour} * * ${dow}`,String(req.body.content||"")]);res.redirect("/automation");});
extrasRouter.post("/automation/scheduled/:id/toggle",async(req:any,res)=>{await query(`UPDATE scheduled_messages SET enabled=NOT enabled WHERE id=$1 AND guild_id=$2`,[req.params.id,selectedGuildId(req)]);res.redirect("/automation");});
extrasRouter.post("/automation/scheduled/:id/delete",async(req:any,res)=>{await query(`DELETE FROM scheduled_messages WHERE id=$1 AND guild_id=$2`,[req.params.id,selectedGuildId(req)]);res.redirect("/automation");});

extrasRouter.get("/commands",async(req:any,res)=>{const raw=[...commandData,...billingCommandData,...economyCommandData,...featureCommandData] as any[];const names=[...new Set(raw.map(c=>c.name))].sort();const rows=await query<any>(`SELECT * FROM command_settings WHERE guild_id=$1`,[selectedGuildId(req)]);res.render("commands",{user:req.session.user,names,settings:new Map(rows.map(r=>[r.command_name,r])),...await guildUi(req)});});
extrasRouter.post("/commands/:name",async(req:any,res)=>{const roles=Array.isArray(req.body.roles)?req.body.roles:req.body.roles?[req.body.roles]:[],channels=Array.isArray(req.body.channels)?req.body.channels:req.body.channels?[req.body.channels]:[];await query(`INSERT INTO command_settings(guild_id,command_name,enabled,role_ids,channel_ids,premium_only,updated_at) VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT(guild_id,command_name) DO UPDATE SET enabled=$3,role_ids=$4,channel_ids=$5,premium_only=$6,updated_at=now()`,[selectedGuildId(req),req.params.name,req.body.enabled==="on",roles,channels,req.body.premiumOnly==="on"]);res.redirect("/commands");});

extrasRouter.get("/health-check",async(req:any,res)=>res.json(await health(req)));
