import { Router } from "express";
import { ChannelType, GuildScheduledEventEntityType, GuildScheduledEventPrivacyLevel, TextChannel } from "discord.js";
import { client } from "./bot.js";
import { config } from "./config.js";
import { one } from "./db.js";

export const nativeDiscordRouter=Router();
const auth=(req:any,res:any,next:any)=>req.session?.user?next():res.redirect("/login");
nativeDiscordRouter.use(auth);

nativeDiscordRouter.get("/discord",async(req:any,res)=>{const g=client.guilds.cache.get(config.targetGuildId);if(!g)return res.status(503).send("Discord is offline");const roleMenus=await one<any>(`SELECT config FROM feature_settings WHERE guild_id=$1 AND feature_key='role_menus'`,[g.id]);res.render("discord-native",{user:req.session.user,guild:g,channels:[...g.channels.cache.values()].sort((a,b)=>a.name.localeCompare(b.name)),roles:[...g.roles.cache.values()].filter(r=>r.id!==g.id).sort((a,b)=>b.position-a.position),roleMenus:roleMenus?.config||{},message:req.query.message||"",error:req.query.error||""});});

nativeDiscordRouter.post("/discord/forum",async(req:any,res)=>{try{const g=client.guilds.cache.get(config.targetGuildId);if(!g)throw new Error("Discord offline");await g.channels.create({name:String(req.body.name||"community-forum").toLowerCase().replace(/[^a-z0-9-]/g,"-"),type:ChannelType.GuildForum,topic:String(req.body.topic||"Organised community discussions and guides"),defaultAutoArchiveDuration:1440});res.redirect("/discord?message="+encodeURIComponent("Forum channel created"));}catch(e:any){res.redirect("/discord?error="+encodeURIComponent(e.message));}});

nativeDiscordRouter.post("/discord/poll",async(req:any,res)=>{try{const ch=await client.channels.fetch(String(req.body.channelId)).catch(()=>null);if(!ch?.isTextBased())throw new Error("Choose a text channel");const answers=String(req.body.answers||"").split(/\n/).map(x=>x.trim()).filter(Boolean).slice(0,10);if(answers.length<2)throw new Error("Add at least two answers");await (ch as TextChannel).send({poll:{question:{text:String(req.body.question).slice(0,300)},answers:answers.map(a=>({text:a.slice(0,55)})),duration:Number(req.body.duration||24),allowMultiselect:req.body.multiselect==="on"}});res.redirect("/discord?message="+encodeURIComponent("Native Discord poll posted"));}catch(e:any){res.redirect("/discord?error="+encodeURIComponent(e.message));}});

nativeDiscordRouter.post("/discord/event",async(req:any,res)=>{try{const g=client.guilds.cache.get(config.targetGuildId);if(!g)throw new Error("Discord offline");const start=new Date(String(req.body.startsAt));if(!Number.isFinite(start.getTime()))throw new Error("Choose a valid start time");const duration=Math.max(15,Number(req.body.duration||60));await g.scheduledEvents.create({name:String(req.body.name).slice(0,100),description:String(req.body.description||"").slice(0,1000),scheduledStartTime:start,scheduledEndTime:new Date(start.getTime()+duration*60000),privacyLevel:GuildScheduledEventPrivacyLevel.GuildOnly,entityType:GuildScheduledEventEntityType.External,entityMetadata:{location:String(req.body.location||"Discord")}});res.redirect("/discord?message="+encodeURIComponent("Discord event created"));}catch(e:any){res.redirect("/discord?error="+encodeURIComponent(e.message));}});

nativeDiscordRouter.post("/discord/onboarding",async(req:any,res)=>{try{const g=client.guilds.cache.get(config.targetGuildId);if(!g)throw new Error("Discord offline");if(!g.features.includes("COMMUNITY" as any))throw new Error("Discord Community must be enabled on the server first");const roleMenus=await one<any>(`SELECT config FROM feature_settings WHERE guild_id=$1 AND feature_key='role_menus'`,[g.id]);const groups=(roleMenus?.config?.groups||[]).filter((x:any)=>x.name&&x.roleIds?.length);if(!groups.length)throw new Error("Create your role groups in EAFC.Live Control first");const defaultIds=String(req.body.defaultChannelIds||"").split(",").map(x=>x.trim()).filter(Boolean);const prompts=groups.map((group:any)=>({type:0,title:String(group.name).slice(0,100),single_select:Number(group.maxSelect||1)===1,required:false,in_onboarding:true,options:group.roleIds.map((roleId:string)=>({title:(g.roles.cache.get(roleId)?.name||"Role").slice(0,100),role_ids:[roleId],channel_ids:[]}))}));const response=await fetch(`https://discord.com/api/v10/guilds/${g.id}/onboarding`,{method:"PUT",headers:{Authorization:`Bot ${config.discordToken}`,"content-type":"application/json"},body:JSON.stringify({prompts,default_channel_ids:defaultIds,enabled:true,mode:0})});if(!response.ok)throw new Error(`Discord rejected onboarding setup (${response.status}): ${(await response.text()).slice(0,300)}`);res.redirect("/discord?message="+encodeURIComponent("Discord Community Onboarding synced"));}catch(e:any){res.redirect("/discord?error="+encodeURIComponent(e.message));}});
