import { Client, PermissionFlagsBits, SlashCommandBuilder, TextChannel } from "discord.js";
import { audit, getFeature, one, query } from "./db.js";
import { systemEmbed, BRAND } from "./brand.js";

export const ticketOpsCommandData=[
 new SlashCommandBuilder().setName("ticketstaff").setDescription("Staff ticket controls").setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels)
  .addSubcommand(s=>s.setName("claim").setDescription("Claim the current ticket"))
  .addSubcommand(s=>s.setName("note").setDescription("Add an internal ticket note").addStringOption(o=>o.setName("note").setDescription("Note").setRequired(true)))
  .addSubcommand(s=>s.setName("close").setDescription("Close this ticket and save a transcript").addStringOption(o=>o.setName("reason").setDescription("Close reason").setRequired(true)))
].map(c=>c.toJSON());

export async function handleTicketOps(client:Client,i:any){if(i.commandName!=="ticketstaff"||!i.guildId)return false;const ticket=await one<any>(`SELECT * FROM tickets WHERE guild_id=$1 AND channel_id=$2 AND status='OPEN'`,[i.guildId,i.channelId]);if(!ticket){await i.reply({content:"This channel is not an open ticket.",ephemeral:true});return true;}const sub=i.options.getSubcommand();if(sub==="claim"){await query(`UPDATE tickets SET claimed_by=$1 WHERE id=$2`,[i.user.id,ticket.id]);await i.reply(`🙋 ${i.user} claimed this ticket.`);await audit(i.guildId,i.user.id,"ticket.claim",{id:ticket.id});return true;}if(sub==="note"){const note=i.options.getString("note",true);await query(`INSERT INTO staff_notes(guild_id,user_id,staff_id,note) VALUES($1,$2,$3,$4)`,[i.guildId,ticket.user_id,i.user.id,`Ticket #${ticket.id}: ${note}`]);await i.reply({content:"📝 Internal note saved.",ephemeral:true});return true;}const reason=i.options.getString("reason",true),ch=await client.channels.fetch(i.channelId).catch(()=>null);let transcript="";if(ch?.isTextBased()){const msgs=await (ch as TextChannel).messages.fetch({limit:100});transcript=[...msgs.values()].reverse().map(m=>`[${m.createdAt.toISOString()}] ${m.author.tag}: ${m.cleanContent}`).join("\n").slice(0,100000);}await query(`UPDATE tickets SET status='CLOSED',close_reason=$1,transcript=$2,closed_at=now() WHERE id=$3`,[reason,transcript,ticket.id]);const feature=await getFeature(i.guildId,"tickets",{logChannelId:"",reviewChannelId:""});await query(`INSERT INTO ticket_reviews(guild_id,ticket_id,user_id,handled_by,closed_by,ticket_type,feedback) VALUES($1,$2,$3,$4,$5,$6,$7)`,[i.guildId,ticket.id,ticket.user_id,ticket.claimed_by||null,i.user.id,ticket.ticket_type,reason]).catch(()=>{});const targetId=feature.config.reviewChannelId||feature.config.logChannelId;if(targetId){const log=await client.channels.fetch(String(targetId)).catch(()=>null);if(log?.isTextBased())await (log as TextChannel).send({embeds:[systemEmbed("⭐ Ticket Review",`A ticket has just been resolved.\n\n**Ticket Type**\n${ticket.ticket_type}\n**Requester**\n<@${ticket.user_id}>\n**Handled By**\n${ticket.claimed_by?`<@${ticket.claimed_by}>`:"Not claimed"}\n**Closed By**\n${i.user}\n**Feedback**\n${reason}`,BRAND.colours.success)]});}await audit(i.guildId,i.user.id,"ticket.close",{id:ticket.id,reason});await i.reply("🔒 Ticket closed. Transcript saved. This channel will be deleted in 5 seconds.");setTimeout(()=>{void (ch as any)?.delete(`Ticket #${ticket.id} closed: ${reason}`).catch(()=>{});},5000);return true;}
